[workspace]

members = ["runtime", "server", "cli"]
resolver = "2"
package.rust-version = "1.80.1"

[workspace.dependencies]
url = { version = "< 2.5.0", features = ["serde", "expose_internals"] }
redb = "2.1.1"
serde = "1.0.208"
tokio = "1.39.2"

deno_console = "0.164.0"
deno_core = "0.299.0"
deno_webidl = "0.164.0"
deno_web = "0.195.0"
deno_crypto = "0.178.0"
deno_fetch = "0.188.0"
deno_net = "0.156.0"
deno_node = "0.100.0"
deno_url = "0.164.0"
anyhow = "1.0.86"
bincode = "1.3.3"
deno_fs = "0.73.0"
