[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
redb = "2.1.1"
server = { path = "../server" }
cloudstate = { path = "../runtime" }
tokio = "1.39.3"
axum = "0.7.5"
notify = "6.1.1"
tower = "0.5.0"
