name: "Publish Artifacts"
on:
  push:
    branches:
      - main

jobs:
  publish-macos-x64:
    name: "Publish macOS x64"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: rustup target add x86_64-apple-darwin
      - name: Build macOS x64 binary
        run: cargo build --release --target x86_64-apple-darwin
      - name: "Create package"
        run: |
          mkdir _package
          mkdir _package/bin
          cp target/x86_64-apple-darwin/release/cloudstate _package/bin/cloudstate
          cp cli/package.json/darwin-x64-package.json _package/package.json
          cp README.md _package/README.md
          (echo "# THIS IS A DEPENDENCY OF [freestyle-sh](https://www.npmjs.com/package/freestyle-sh) AND SHOULD NOT BE USED DIRECTLY"; cat _package/README.md) > _package/README.md.tmp
          mv _package/README.md.tmp _package/README.md
      - name: "Version"
        working-directory: _package
        run: |
          npm version --no-git-tag-version $(npm view cloudstate-darwin-x64@latest version)
          npm version --no-git-tag-version prerelease
      - name: "Publish"
        working-directory: _package
        env: 
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
        run: |
          npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish

  publish-macos-arm64:
    name: "Publish macOS arm64"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build macOS arm64 binary
        run: cargo build --release --target aarch64-apple-darwin
      - name: "Create package"
        run: |
          mkdir _package
          mkdir _package/bin
          cp target/aarch64-apple-darwin/release/cloudstate _package/bin/cloudstate
          cp cli/package.json/darwin-arm64-package.json _package/package.json
          cp README.md _package/README.md
          (echo "# THIS IS A DEPENDENCY OF [freestyle-sh](https://www.npmjs.com/package/freestyle-sh) AND SHOULD NOT BE USED DIRECTLY"; cat _package/README.md) > _package/README.md.tmp
          mv _package/README.md.tmp _package/README.md
      - name: "Version"
        working-directory: _package
        run: |
          npm version --no-git-tag-version $(npm view cloudstate-darwin-arm64@latest version)
          npm version --no-git-tag-version prerelease
      - name: "Publish"
        working-directory: _package
        env: 
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
        run: |
          npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish


      # - name: Upload macOS arm64 binary
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: macos-arm64

