name: "Publish Artifacts"
on:
  push:
    branches:
      - main

jobs:
      
  publish-macos-arm64:
    name: "Publish macOS arm64"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release --target aarch64-apple-darwin
      - run: mkdir _package && mkdir _package/bin
      - run: cp target/release/cloudstate _package/bin/cloudstate
      - run: cp cli/package.json/macos-package.json _package/package.json
      

      - run: echo _auth=$NPM_PUBLSH_KEY >> .npmrc
      - run: echo email=<youremail> >> .npmrc
      - run: echo always-auth=true >> .npmrc
      - name: "Publish"
        working-directory: _package
        run: |
          npm version --no-git-tag-version $(npm view cloudstate-macos-arm64@latest version)
          npm version --no-git-tag-version prerelease
          npm publish --tag beta


      # - name: Upload macOS arm64 binary
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: macos-arm64

