name: "Publish Artifacts"
on:
  push:
    branches:
      - main

jobs:
      
  publish-macos-arm64:
    name: "Publish macOS arm64"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build macOS arm64 binary
        run: cargo build --release --target aarch64-apple-darwin
      - name: "Create package"
        run: |
          mkdir _package
          mkdir _package/bin
          cp target/aarch64-apple-darwin/release/cloudstate _package/bin/cloudstate
          cp cli/package.json/darwin-package.json _package/package.json
      - name: "Setup NPM"
        run: |
          echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > .npmrc
        env: # Or as an environment variable
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
      - name: "Version"
        working-directory: _package
        run: |
          npm version --no-git-tag-version $(npm view cloudstate-darwin-arm64@latest version)
          npm version --no-git-tag-version prerelease
      - name: "Publish"
        working-directory: _package
        run: |
          npm publish


      # - name: Upload macOS arm64 binary
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: macos-arm64

